version: '3'
services:
  web:
    build: 
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
    - "8000:80"
    links:
    - node
#    command: "cd ./angular-app && npm install"
    volumes:
    - "/angular/angular-app/dist/out:/usr/share/nginx/html"
  node:
    build: 
      context: ./node-service
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo
    ports: 
    - "27017:27017"
