version: '3'
services:
  web:
    image: web
    build: ./angular-app
    ports:
    - "8000:80"
    links:
    - node
    #command: 'cd /usr/share/nginx/html/angular/angular-app && npm build --prod'
    volumes:
    - "./angular-app/dist/out:/usr/share/nginx/html"
    - "./angular-app/nginx.conf:/etc/nginx/nginx.conf:ro"
  node:
    image: node
    build: ./node-service
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo
    ports: 
    - "27017:27017"
